---

- name: Airflow | Ensure airflow directories structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
  with_items:
    - "{{ airflow_logs_folder }}"
    - "{{ airflow_child_process_log_folder }}"
    - "{{ airflow_dags_folder }}"
    - "{{ airflow_plugins_folder }}"
    - "{{ airflow_conf_path }}"

- name: Airflow | Copy gunicorn logrotate config
  template:
    src: gunicorn-logrotate.j2
    dest: /etc/logrotate.d/airflow
    mode: 0644
    owner: root
    group: root
  tags: airflow-gunicorn-logrotate

- name: Airflow | Copy webserver_config.py file
  template:
    src: webserver_config.j2
    dest: "{{ airflow_app_home }}/webserver_config.py"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0644
  register: airflow_config
  when: airflow_version is version( '2.0.0', '>=')
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower
  tags: airflow-webserver-config-py

- name: Airflow | Copy basic airflow config file (< 2.0)
  template:
    src: "{{ airflow_config_template_path }}"
    dest: "{{ airflow_conf_path }}/airflow.cfg"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  register: airflow_config
  when: airflow_version is version( '2.0.0', '<')
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower
  tags: airflow-cfg

- name: Airflow | Copy basic airflow config file (>= 2.0)
  template:
    src: "{{ airflow_config_template_path_v2 }}"
    dest: "{{ airflow_conf_path }}/airflow.cfg"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  register: airflow_config
  when: airflow_version is version( '2.0.0', '>=')
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower
  tags: airflow-cfg

- name: Airflow | Initializing DB < 2.0
  command: "{{ airflow_executable }} initdb"
  become: true
  become_user: "{{ airflow_user }}"
  when:
    - airflow_version is version( '2.0.0', '<')
    - (airflow_install.changed or airflow_config.changed)
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower
  tags:
    - airflow-db-init
    - skip_ansible_lint

- name: Airflow | Initializing DB > 2.0
  command: "{{ airflow_executable }} db init"
  environment:
    AIRFLOW_HOME: "{{ airflow_app_home }}"
    AIRFLOW_CONFIG: /etc/airflow/airflow.cfg
  become: true
  become_user: "{{ airflow_user }}"
  when:
    - airflow_version is version( '2.0.0', '>=')
    - airflow_install.changed or airflow_config.changed
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower
  tags: airflow-db-init

- name: Airflow | Copy extra airflow config files (provided by playbooks)
  copy:
    src: "{{ item }}"
    dest: "{{ airflow_conf_path }}/{{ item | basename }}"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  with_fileglob:
    - "{{ airflow_extra_conf_path }}/*"
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower
  tags: airflow-extra-config

- name: Airflow | Copy extra airflow config templates (provided by playbooks)
  template:
    src: "{{ item }}"
    dest: "{{ airflow_conf_path }}/{{ item | basename }}"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  with_fileglob:
    - "{{ airflow_extra_conf_template_path }}/*"
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower
  tags: airflow-extra-config

- name: Airflow | Add variables from configuration file
  command: "{{ airflow_executable }} variables -s {{ item.key }} {{ item.value }}"
  become: true
  become_user: "{{ airflow_user }}"
  with_items: "{{ airflow_admin_variables }}"
  tags:
    - skip_ansible_lint
    - airflow-extra-vars-file

- name: Airflow | Add connections from configuration file
  become: true
  become_user: "{{ airflow_user }}"
  environment:
    AIRFLOW_HOME: "{{ airflow_app_home }}"
    AIRFLOW_CONFIG: /etc/airflow/airflow.cfg
  command: "{{ airflow_executable }} connections add \
  {% for key, value in item['properties'].items() %}--{{ key }} '{{ value }}' \
  {% endfor %} {{ item['name'] }}"
  with_items: "{{ airflow_admin_connections }}"
  tags:
    - skip_ansible_lint
    - airflow-extra-conn-file