---

- name: Airflow | Configuring service
  systemd:
    name: "{{ item.value.service_name }}"
    state: "{{ item.value.state }}"
    enabled: "{{ item.value.enabled }}"
    daemon_reload: true
  with_dict: "{{ airflow_services }}"
  when: item.value.enabled
  changed_when: false
